Lencerf/vscode-beancount

src/extension.ts
When inserting new lines under a transaction the extension automatically adds some spaces. This is nice, but I have my editor set to use 2 as the tabSize and it would be nice if the extension honored that setting.
I just realised that these diffs contain more changes than they should. This is because my editor automatically trims whitespace at the end of a line and I forgot about that before I committed. Please let me know if this is a problem.
=> Made the extension honor editor.tabSize when inserting new postings

README.md, package.json, snippets/beancount.json
Adds code snippets for all directives. Includes custom budget snippet for Fava. I have tested the snippets themselves as an "user snippets". I have not debugged the extension (do not have `Node.js` set up on this machine) so the correctness of the config needs to be tested.
=> Add Beancount and Fava snippets.

src/extension.ts
The extension wasn't functioning correctly for me. I tracked it down to the fact that it was regularly receiving a TextDocumentChangeEvent with an empty contentChanges array. This change just bails out if an empty contentChanges array is passed in...
=> protect against empty contentChanges arrays

language-configuration.json
Following the recommendations [here](https://code.visualstudio.com/updates/v1_17#_folding-regions), it seems like `;#region` fits the best.
Since [lines with non-valid beancount syntax are ignored](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.9zjhwskw53j8), one alternative would be to directly use `#region`. However, using explicit comments seems cleaner to me and provides better syntax highlighting (if going down this route, new syntax highlighting could be added).
See: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages
Fixes #5
=> Add code folding markers

README.md, syntaxes/beancount.tmLanguage
When using region folding through indentation in VSCode, this extension didn't recognize directives, because the language grammar explicitly looked for the start of the line. I'm allowing whitespace since beancount itself supports it (I've been using it with my personal ledger).
Also documented the folding syntax from the `README` for others starting out.
=> Recognize indented directives

package-lock.json, package.json, pythonFiles/beancheck.py, src/extension.ts
This adds warnings in the VSCode "problems" pane for flagged transactions/postings. The severity level is customizable per flag, and includes an option to disable warnings for a particular flag. By default only the warning flag (`!`) results in a warning, at the "warning" level in VSCode.
=> Add warning messages for flagged items

src/actionProvider.ts, src/extension.ts
Add a quick fix action to mark a flagged transaction as okay.
I didn't bump the version in this change; not sure if this change can be added to 0.3.6 or if a version bump is required. If it is, I'm happy to make that change.
=> Add "flag as okay" quickfix for flag warnings

src/formatter.ts
Previously the formatter uses global `editor.tabSize` as tab size, and ignores language specific settings such as `"[beancount]": {"editor.tabSize": 2}`. This update makes formatter use the correct `tabSize` for the currently active editor.
=> Make formatter aware of language specific tabSize settings

syntaxes/beancount.tmLanguage
Previously, accounts that started with one of the `PSTCURM` characters weren't highlighted correctly in transactions.
This ensures that flags only match if they are succeeded by a whitespace character.
Before:
After:
=> Ensure accounts in transaction can start with all letters

src/extension.ts, src/utils.ts
This PR allows configuring a workspace relative path to python.
I don't have Beancount installed globally, but use https://direnv.net together with https://nixos.org/nixpkgs/ to handle project dependencies.
Beancount + Fava are packaged with a nix-generated python wrapper script, that includes all the `PYTHONPATH` variables etc. so that python can find all library dependencies.
I tried to make vscode-beancount run this script  and discovered it does not `spawn` from workspace. This PR fixes that.
=> Support relative path to python (to allow wrapper scripts)

syntaxes/beancount.tmLanguage
This PR adds support to the following syntax:
* `plugin` without arguments
* `transaction` without payee or narration
* tag, link and comment without preceding spaces
* meta key with underscore
* meta values of various types
* `custom` with arguments of various types
It also fixes some minor problems:
* escapes `&` in syntax file as `&amp;` instead of the original `&amp;amp;`
* disallows `2019-01-01 padAssets:Foo` (without space between directive and account)
It doesn't seem quite testable so only some manual testing. Might not be sufficient.
=> Syntax Highlight Enhancement

snippets/beancount.json
According to the manual of beancount, the commidity meta data `assets-class` should be `asset-class` 
https://beancount.github.io/docs/beancount_language_syntax.html#commodity
=> chage assets-class to asset-class

README.md, package.json, src/formatter.ts
Adding a new option `beancount.fixedCJKWidth` to treat CJK aka East Asian characters as two letters width on alignment.
It makes alignment work properly with CJK characters in account name and fixed pitched fonts.
The East Asian Wide characters range comes from UTR #11 - Unicode Character Property "East Asian Width" http://www.unicode.org/reports/tr11-2/.
=> Treat CJK aka East Asian characters as two letters width.

src/completer.ts
Fix the issue #68 by skipping the closed account.
Verified in my environment with below test file:
```beancount
2022-01-29 open Assets:Test1 USD
2022-01-29 open Assets:Test2 USD
2022-01-30 close Assets:Test1
2022-01-31 * "Test"
Asset
```
Verify result:
=> Skip closed accounts when prompting complete items

src/completer.ts, src/inputMethods/inputMethod.ts, src/inputMethods/pinyin.ts, src/utils.ts
This PR extends the "input method" feature to acount name so that input of acount name can be benifited from current pinyin support on "payee" input.
=> "Input Method" Support on Account Name

syntaxes/beancount.tmLanguage
Let's fix the scope name, because
- none of most popular dark themes has a theme selector for `entity.type.*`, but rather every theme has a selector for a `entity.name.type.*`.
- the two guides linked in vscode scoping docs ([1](https://macromates.com/manual/en/language_grammars), [2](https://www.sublimetext.com/docs/scope_naming.html)) suggest to use `entity.name.type`
| before (dark modern theme) | after (dark modern theme) |
|--------|--------|
| ![image](https://github.com/Lencerf/vscode-beancount/assets/7459419/d1ca5c34-53d6-4ed5-af8f-1c3a50c637dd) | ![image](https://github.com/Lencerf/vscode-beancount/assets/7459419/e6e54e9a-77bb-4abf-875d-5db7b145e8f7) |
=> fix(syntax): "name" in "entity.name.type"

syntaxes/beancount.tmLanguage
As per two guides linked in vscode scoping docs ([1](https://macromates.com/manual/en/language_grammars), [2](https://www.sublimetext.com/docs/scope_naming.html)) all other variables should be classified under `variable.other`. In practice, indeed, several themes have a specific scope for `variable.other`, see the table below.
| theme | before | after |
|--------|--------|--------|
| Github Dark | ![image](https://github.com/Lencerf/vscode-beancount/assets/7459419/9825dc9a-a652-42c4-895d-d1ddaa7c3449)  | ![image](https://github.com/Lencerf/vscode-beancount/assets/7459419/36b7abfe-6a4f-4870-aef3-97e5fe55f478) |
| Solarized Dark | ![image](https://github.com/Lencerf/vscode-beancount/assets/7459419/2ff15530-bc57-4cda-8a33-89e0a86fddce) | …
=> fix(syntax): "other" in "variable.other.account"

syntaxes/beancount.tmLanguage
Conceptually, I find it weird that first half of account is a constant (`constant.language.*`) and the latter part of it is variable (`variable.*`). I suggest to use `variable.language` for the first part to align both sides of account consistently to the idea that accounts are visually represented as variables.
Practically, here are screenshots for various popular themes (includes #93 changes). The way how either of two colors looks together with latter part of account depends likely depends on taste, but generally I don't see nothing obviously wrong in any of cases. IMHO a general improvement is that in all cases former part of account is more different or similar compared to the date above it.
| theme | before | after |
|--------|--------|--------|
| Ayu Dark | …
=> feat(syntax): account name prefix as "variable.language"

README.md
vscode provides an api for registering folding range provider that is [used by vscode-org-mode](https://github.com/vscode-org-mode/vscode-org-mode/blob/98f123a97eca8d0cc1d9e3f313dc2a8be8f25d46/src/extension.ts#L61) for org-mode style folding.
But since the vscode-org-mode extension hasn't been updated for a long time and has GPLV3 license which is not compatible with this repository's MIT license, I have separated the org style code folding from the above repo into a separate extension call org-mode-fold. 
Works as expected with this extension, on my testing.
=> Add org-mode-fold to README.md

package.json, src/documentLinkProvider.ts, src/extension.ts, src/utils.ts
This PR tries to address the issue #79 by adding a new `DocumentLinkProvider` to detect file links specified by `include` directive and provide them as clickable DocumentLinks.
Demo:
During testing, I've noticed the two languages specified in package.json `beancount` and `beancount-oneline` could have conflicts which could cause language providers (such as this DocumentLinkProvider) not working without changing the extension names of the `beancount-oneline`.
For the simplicity of this PR, I didn't fix it here, but I have opened another issue to track it.
=> Support opening files from 'include' directive by adding DocumentLinkProvider

src/symbolProvider.ts
This PR adds support for multi-levels code outline from headings ([issue 108)](https://github.com/Lencerf/vscode-beancount/issues/108) 
An example of a beancount file:
```
*  1 L1
** 1.1 L2
*** 1.1.1 L3
**** 1.1.1.1 L4
**** 1.1.1.2 L4
***** 1.1.1.2.1 L5
**** 1.1.1.3 L4
* 2 L1
**** 2.1.1.1 L4 after 2 levels were skipped
```
Current functionality
New functionality
Note, that in the example, it also handles correctly the situation, when some levels of headings where skipped
=> Adding support for multi-level code outline from headings

package.json, pythonFiles/beancheck.py, src/extension.ts, src/inlayHints.ts
In some complicated transactions where I have not specified the amount in the last leg of the transaction, I still want to view the value that beancount has inferred.
This PR adds support for exactly this scenario by adding inlay hints for such postings.
It only adds the hints for non-trivial transactions, which are either:
1. Transctions with more than two legs
2. Transactions dealing with multiple commodities
(Open to suggestions on more scenarios)
The extension does not actually calculate the balance amount, so the inlay hints are not real-time. They will show up only after a `bean-check` run on the file(s), usually triggered by a file save.
TODO:
=> Add Inlay Hints for last legs of transactions with elided amounts

pythonFiles/beancheck.py
The extension does not function correctly if there are any calls to `print()` from `loader.load_file()` e.g. from a beancount plugin that has print() statements.
PR to silence any such print statements using: https://stackoverflow.com/a/8391735.
=> Silence print calls from loader.load_file

syntaxes/beancount.tmLanguage
So that color themes may color the two differently (for example, coloring `*` with green and `!` with red).
=> Differentiate between different transaction flags
